apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    name: backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32012
  selector:
    name: backend
  type: NodePort
